### ISSUE TITLE
My install broke due to change in bambu plugin, changed camera from image to camera entity.

### ISSUE THREAD

**Issue by ForceConstant** [nobodyguy/obico_ml_ha_integration#3]
I know this plugin isn't specific to Bambu printers, but maybe you can help. So previously everything was working, but last week the Bambu plugin was update, which changed the camera feed in HA to be a camera model instead of just an image, which is causing this plugin to not to trigger any updates sent to obico. Any ideas?

**Comment by nobodyguy** [comment]
The camera image property is probably not correctly used by the Bambu integration:
https://github.com/greghesp/ha-bambulab/pull/595#issuecomment-2437354522

The Obico integration just does GET request to URL in format of: `https://XYZ/api/camera_proxy_stream/camera.your_camera_entity?token=XXX` and that probably fails.
Feel free to share the HA logs to the mentioned issue to investigate it (or revert back to the previous working version).

**Comment by AdrianGarside** [comment]
This is an example URL for the camera: 
```http://10.10.10.5:8123/api/camera_proxy_stream/camera.p1s_<SERIAL>_camera?token=<TOKEN>```
It renders correctly in a web browser tab.

As part of the image -> camera transition, the entity name changed from image.p1s_<SERIAL>_camera to camera.ps1_<SERIAL>_camera. It's not clear if they changed the obico configuration to use the new entity name.

**Comment by AdrianGarside** [comment]
> This is an example URL for the camera: `http://10.10.10.5:8123/api/camera_proxy_stream/camera.p1s_<SERIAL>_camera?token=<TOKEN>` It renders correctly in a web browser tab.
> 
> As part of the image -> camera transition, the entity name changed from image.p1s__camera to camera.ps1__camera. It's not clear if they changed the obico configuration to use the new entity name.

**Comment by nobodyguy** [comment]
> This is an example URL for the camera: `http://10.10.10.5:8123/api/camera_proxy_stream/camera.p1s_<SERIAL>_camera?token=<TOKEN>` It renders correctly in a web browser tab.
> 
> As part of the image -> camera transition, the entity name changed from image.p1s__camera to camera.ps1__camera. It's not clear if they changed the obico configuration to use the new entity name.

Well if the camera entity has changed, you have to update the Obico ML integration config flow. If the updating doesn't help, try to remove it and configure it again.
In case it still doesn't work, post Obico ML integration's logs and Obico REST API server's logs here please.

**Comment by ForceConstant** [comment]
So I verified that yes that url does work for the camera stream, so that didn't change. I ended up deleting the plugin, and re-adding the entity, and everything is working again. So not sure what happened. Thanks.

**Comment by nobodyguy** [comment]
> So I verified that yes that url does work for the camera stream, so that didn't change. I ended up deleting the plugin, and re-adding the entity, and everything is working again. So not sure what happened. Thanks.

Thanks for the update.
I think I don't specifically handle reconfiguration and I guess it doesn't work out of the box, so deleting and creating new configuration is needed for now.
